[build]
  # Directory to change to before starting build
  base = "./"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "out"
  
  # Default build command
  command = "npm install --legacy-peer-deps --ignore-engines && (rm -f postcss.config.js tailwind.config.js || true) && npm run build"
  
  # Directory with serverless functions
  functions = "functions"

# Environment variable inheritance
[build.environment]
  NODE_VERSION = "18.17.0"
  # Set a flag to indicate we're using MongoDB by default
  USE_LOCALSTORAGE_FALLBACK = "false"
  NODE_ENV = "production"

# Redirects for Netlify functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  
# Handle SPA routing for Next.js - force SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Make sure to serve JavaScript and CSS files with the correct MIME type
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

# Handle demo shares by exact path
[[redirects]]
  from = "/share/demo_share"
  to = "/share-fallback?id=demo_share"
  status = 200

[[redirects]]
  from = "/share/demo_permalink"
  to = "/share-fallback?id=demo_permalink"
  status = 200

# Handle all other share paths
[[redirects]]
  from = "/share/*"
  to = "/share-fallback?id=:splat"
  status = 200

# Use the Netlify Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Function configuration
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongoose"]

[dev]
  functions = "functions"
  publish = "."
  autoLaunch = false

# Environment variable inheritance
[dev.environment]
  NODE_VERSION = "18.17.0"
  # Set a flag to indicate we're using MongoDB by default
  USE_LOCALSTORAGE_FALLBACK = "false"
  NODE_ENV = "production"

# CORS headers for all API endpoints
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization" 