[build]
  command = "npm run build"
  publish = "out"

# Handle direct access to share IDs
[[redirects]]
  from = "/share/*"
  to = "/share-fallback?id=:splat"
  status = 200

# For all other routes, serve the index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Use the Netlify Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs" 