[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_PUBLIC_BASE_PATH = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle Next.js static files
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  force = true

# Handle Next.js page data
[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200
  force = true

# Handle all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true