[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "out"
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/package.json"]

# Disable the Next.js plugin
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# CORS headers for API endpoints
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Handle OPTIONS requests for CORS
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  conditions = {Methods = ["OPTIONS"]} 