[build]
  command = "npm run build"
  publish = "out"

# Handle demo shares by exact path
[[redirects]]
  from = "/share/demo_share"
  to = "/share-fallback?id=demo_share"
  status = 200

[[redirects]]
  from = "/share/demo_permalink"
  to = "/share-fallback?id=demo_permalink"
  status = 200

# Handle all other share paths
[[redirects]]
  from = "/share/*"
  to = "/share-fallback?id=:splat"
  status = 200

# For all other routes, serve the index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Use the Netlify Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs" 